
version: '3.1'
services:
  app:
    container_name: docker-springboot-postgresql
    image: docker-springboot-postgresql
    build: ./
    ports:
      - "9898:9898"
    depends_on:
      - postgresqldb
  postgresqldb:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=postgres
      - POSTGRES_DB=32bit