spring:
  application:
    name: identity-service

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
    healthcheck:
      enable: true

server:
  port: 9898

